### ISSUE TITLE
multiple usb cameras

### ISSUE THREAD

**Issue by YeetMasterYeet** [duongttr/vehicles-counting-yolov4-deepsort#5]
hello @duongttr,
i have seen the referenced multi image tracking GitHub project, but i want to use multiple usb cameras and not ip cameras, is there a way to do that with this project (run detection, tracking and counting on multiple usb cameras). thank you.

**Comment by duongttr** [comment]
Hi @YeetMasterYeet,

The answer is YES and NO, you can do it with your USB camera by configuring the parameter `video`. The default value of your computer's webcam is 0. With USB camera you can run a `for loop` from 1 to 100 to check the id of that camera set the value for `video=id`. Unfortunately my project can just run on single camera and can't run parallel on multiple camera. I will update that function if I have time.

Thanks for your question!

**Comment by YeetMasterYeet** [comment]
@duongttr hello!
Yes i have been able to run the code on separate usb cameras by changing the Id, it would be interesting to have the option to use more than one camera.
thank you for you reply 😊😊.
