### ISSUE TITLE
crop_object

### ISSUE THREAD

**Issue by farshokat** [duongttr/vehicles-counting-yolov4-deepsort#7]

**Comment by farshokat** [comment]
chào bạn, mình đã tham khảo clone của bạn, nó rất hay vào giúp ích được nhiều người. Bạn cho mình một vấn đề và mong muốn nhận được giúp đỡ của bạn. Hiện tại, t muốn các object khi đi qua đường line sẽ được crop object và capture ảnh. B có thể giúp đỡ mình được không? mình cảm ơn và mong nhận được giúp đỡ của c

**Comment by duongttr** [comment]
Hi @farshokat,

Sorry for late response.
I can handle this task, please contact me through email: duong.jt.19@gmail.com
