### ISSUE TITLE
USB CAMERA

### ISSUE THREAD

**Issue by YeetMasterYeet** [duongttr/vehicles-counting-yolov4-deepsort#8]
hello, i have been using this repository and i cannot seem to make it work using a usb camera. i have been able to run the code on recorded videos, on my integrated camera but i cannot make my usb camera work. 
one thing i noticed in my device managed is that my usb camera does not appear under the camera section, it has its own section as a USB device.
I have tried everything such but nothing seems to work:
- changing the 0 for integrated cam to 1, 2,3...
- giving the camera access path
- trying to place the usb camera under the cam section in device manager.
is there any workaround to this problem or any indication on how to make the camera. thanks.

**Comment by duongttr** [comment]
Hi there,

Where did you pass the id of the camera into? Make sure you pass it to `video` parameter of `VehiclesCounting` class.

**Comment by YeetMasterYeet** [comment]
that is why i have  exactly what i have done and nothing the camera is not detected.
