### ISSUE TITLE
tensorflow installation

### ISSUE THREAD

**Issue by YeetMasterYeet** [duongttr/vehicles-counting-yolov4-deepsort#9]
Hello, i have been trying to install the requirements of this project on a new computer, when i try to install the  gpu requirements using the following command:

`pip install -r requirements-gpu.txt`

 i get this error from tensorflow package:
`ERROR: Could not find a version that satisfies the requirement tensorflow-gpu==2.3.0rc0 (from versions: 1.13.1, 1.13.2, 1.14.0, 1.15.0, 1.15.2, 1.15.3, 1.15.4, 1.15.5, 2.0.0, 2.0.1, 2.0.2, 2.0.3, 2.0.4, 2.1.0, 2.1.1, 2.1.2, 2.1.3, 2.1.4, 2.2.0, 2.2.1, 2.2.2, 2.2.3, 2.3.0, 2.3.1, 2.3.2, 2.3.3, 2.3.4, 2.4.0, 2.4.1, 2.4.2, 2.4.3, 2.4.4, 2.5.0, 2.5.1, 2.5.2, 2.6.0, 2.6.1, 2.6.2, 2.7.0rc0, 2.7.0rc1, 2.7.0)
ERROR: No matching distribution found for tensorflow-gpu==2.3.0rc0
` 
any idea on how i can fix/bypass this problem? thanks.

**Comment by duongttr** [comment]
Hi @YeetMasterYeet,
You can try to use one 1 of the hinted version it shows on the screen but >2.0.0. 

In this case, just replace 2.3.0rc0 with 2.3.0 (without rc0)

**Comment by YeetMasterYeet** [comment]
hello @duongttr , yep that works perfectly, thank you.
